# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    kin_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    #joint_state_broadcaster:
    #  type: joint_state_broadcaster/JointStateBroadcaster

kin_group_controller:
  ros__parameters:
    joints:
      - L1
      - L2
      - L3
      - L4
      - L5
      - L6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
